### ISSUE TITLE
답안 제출이 75~ 개 이상정도 저장이 안되는 현상

### ISSUE THREAD

**Issue by viaSSH** [GSNextLevel/exam-boom#10]
답안 저장 시 쿠키에 저장을 하는데, 이때 브라우저 쿠키의 Max 용량인 4096B 를 넘어서 발생하는 문제

**Comment by boomkim** [comment]
음... 해결방법이 여러가지가 있을것 같은데
1. Localstorage 활용 
2. DynamoDB 활용 
어떤 방식이 좋을까요? 
그냥 브라우저에만 저장할거면 1번이 좋을것 같구 
이력관리 등 생각하면 DDB에 해야될것 같고 하네요.

**Comment by viaSSH** [comment]
1. 임시방안으로 쿠키의 길이제한을 넘지않게 제출가능한 문제 수(75개로)를 줄이고 변수명을 압축하는 방법... => id -> i 로 바꾸고 ans -> a 로 바꾸는 꼼수
2. DDB 에 저장하는 방법도 있는데 조만간 Cognito나 여타 다른 인증 방식을 도입해서 회원관리를 할때 같이 업데이트 할까 고민중입니다

**Comment by boomkim** [comment]
이거 제가 혹시 localstorage 로 변경을 진행해볼까요? 어렵진 않을것 같은데

**Comment by viaSSH** [comment]
넵 ! 근데 코드가 좀 난해해서 알아보기 어려울 수 있는데..... 바꾸는 건 좋습니다 !!

**Comment by boomkim** [comment]
네 뭔가 이번에 하면서 코드도 쪼끔씩 정리해보죠

**Comment by viaSSH** [comment]
쿠키에 저장된 submitAnswer 는 ExamCard.jsx에서 선택한 문제를 저장하고있습니다.

examToolbar에서 코드가 복잡해진 이유는 이미 제출한 문제를 중복으로 채점해서 서버에 등록되는걸 방지하기 위해 이미 제출했던 문제들과 새롭게 푼 문제를 비교하는 요상한 로직이 들어가있어서 그렇습니다....

**Comment by viaSSH** [comment]
`const getAnswerResponse =  await api.getAllExamAnswer(type, frontIdx, endIdx).then(exam => {`

요 부분에서도 frontIdx, endIdx 는 답을 가져올때 일부분만 짤라서 가져오려고했지만 그닥 뭐 효율적인지는 모르겠어요
