### ISSUE TITLE
How-to.md 작성

### ISSUE THREAD

**Issue by boomkim** [GSNextLevel/exam-boom#74]
개발환경 세팅방법 가이드. 

지금은 git clone, npm install, npm start 만 하면 되지만 
백엔드 개발 환경 및 CI/CD 통합을 위해 문서화 필요.

**Comment by heuristicwave** [comment]
세팅 가이드는 레포 Wiki 기능을 적극 활용 합시다!
https://github.com/GSNextLevel/exam-boom/wiki

wiki 홈화면에 Setting Guide 페이지를 만들어 두었습니다.
